name: testenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi=0.112.2
  - pytorch=2.6.0
  - requests=2.32.4
  - streamlit=1.47.0
  - textblob=0.18.0.post0
  - transformers=4.51.3
  - fastapi
  - pip
  - pip:
      - "fastapi[standard]"